#!/bin/bash

# Create Zsh Configuration Script
# Part of the general dotfile collection
# Creates a comprehensive .zshrc file with all necessary configurations

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to create comprehensive .zshrc
create_zshrc() {
    local home_dir="$1"
    local dotfiles_dir="$2"
    local zshrc_file="$home_dir/.zshrc"
    
    print_status "Creating basic .zshrc file..."
    
    # Backup existing .zshrc if it exists
    if [ -f "$zshrc_file" ]; then
        cp "$zshrc_file" "$zshrc_file.backup.$(date +%Y%m%d-%H%M%S)"
        print_status "Backup created: $zshrc_file.backup.$(date +%Y%m%d-%H%M%S)"
    fi
    
    # Create basic .zshrc
    cat > "$zshrc_file" << 'EOF'
# =============================================================================
# Basic Zsh Configuration
# Generated by dotfiles bootstrap script
# =============================================================================

# =============================================================================
# Oh My Zsh Configuration
# =============================================================================

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Basic theme (minimal)
ZSH_THEME=""

# =============================================================================
# Essential Plugins Only
# =============================================================================

# Essential plugins for productivity
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    zsh-completions
)

# =============================================================================
# Load Oh My Zsh
# =============================================================================

source $ZSH/oh-my-zsh.sh

# =============================================================================
# Basic Environment Variables
# =============================================================================

# Add custom paths if they exist
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

if [ -d "$HOME/bin" ]; then
    export PATH="$HOME/bin:$PATH"
fi

# =============================================================================
# Basic History Configuration
# =============================================================================

# History settings
HISTSIZE=5000
SAVEHIST=5000
HISTFILE=~/.zsh_history
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_REDUCE_BLANKS

# =============================================================================
# Basic Completions
# =============================================================================

# Initialize completion system
autoload -U compinit && compinit

# =============================================================================
# Source Dotfiles Aliases
# =============================================================================

EOF

    # Add the dotfiles aliases source line
    echo "# Source dotfiles aliases" >> "$zshrc_file"
    echo "source \"$dotfiles_dir/.aliases\"" >> "$zshrc_file"
    
    # Add final section
    cat >> "$zshrc_file" << 'EOF'

# =============================================================================
# End of Configuration
# =============================================================================

# Basic prompt (if no theme is set)
if [ -z "$ZSH_THEME" ]; then
    PROMPT='%n@%m %~ %# '
fi
EOF

    print_success "Basic .zshrc created at $zshrc_file"
}

# Main function
main() {
    echo -e "${BLUE}🔧 Creating Zsh Configuration${NC}"
    echo "=================================="
    
    local home_dir="$HOME"
    local dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
    
    print_status "Home directory: $home_dir"
    print_status "Dotfiles directory: $dotfiles_dir"
    
    # Create comprehensive .zshrc
    create_zshrc "$home_dir" "$dotfiles_dir"
    
    print_success "Zsh configuration created successfully!"
    echo ""
    print_status "The .zshrc file includes:"
    echo "  - Oh My Zsh configuration"
    echo "  - All necessary plugins"
    echo "  - Environment variables"
    echo "  - History settings"
    echo "  - Key bindings"
    echo "  - Dotfiles aliases integration"
    echo ""
    print_status "To apply the configuration:"
    print_status "  - Restart your terminal"
    print_status "  - Or run: source ~/.zshrc"
} 